### ISSUE TITLE
Feature request: Make Footer a Component and Add Links

### ISSUE THREAD

**Issue by berntpopp** [halbritter-lab/nc-scorer#3]
### Description
Refactor the footer into a Vue component and enhance it by adding useful links.

### Tasks
- [ ] Create a `Footer.vue` component.
- [ ] Add links to relevant resources, such as documentation, repository, etc.
- [ ] Integrate the `Footer` component into `App.vue`.

### Acceptance Criteria
- The footer is modular and contains additional links.
- All links are functional and lead to the correct resources.
